### ISSUE TITLE
core dev lint

### ISSUE THREAD

**Issue by Mazuh** [EvoluxBR/react-smart-tabs#44]
PRs are having too much review noise about styling. Does everyone agree with setting a lint/prettier? cc @gustavoFreireS @davidcostadev

**Comment by gustavoFreireS** [comment]
I did set up TSlint  but seems like its deprecated (and a lot of rules are missing) as you can see here https://github.com/palantir/tslint in favor of https://github.com/typescript-eslint/typescript-eslint, I guess @davidcostadev could help setting up proper rules since it's the same as using eslint, I have prettier installed on my editor recently with default rules but did not set up a .prettierrc for the project
